import ContactWidget from "./ContactWidget";
import { LOGIN_URL, SIGNUP_URL } from "./story";

const DEMO_URL = "https://calendly.com/kontakt-vinyos/30min";

// Inhalte aus der bestehenden Marketingseite, sprachlich für den neuen Entwurf überarbeitet.
const PLANS = [
  { name: "Starter", id: "starter", price: "189", count: "150", feature: "Team-Mitglieder", trial: true },
  { name: "Pro", id: "pro", price: "349", count: "350", feature: "Team-Mitglieder", trial: false },
  { name: "Enterprise", id: "enterprise", price: "579", count: "700", feature: "Prioritäts-Support", trial: false },
];
const FAQ = [
  ["Welche Dateien benötige ich?", "Vinyos Quote verarbeitet technische Zeichnungen als PDF und 3D-Modelle im STEP-Format (.stp oder .step). Wenn die Dateinamen übereinstimmen, werden PDF und STEP automatisch als Paar erkannt."],
  ["Wie entsteht der Preis?", "Die Kalkulation berechnet Schnittzeiten, Rüstkosten und Material regelbasiert mit Ihren Stundensätzen und Ihrer Marge. Sie prüfen den Vorschlag und können ihn vor der Freigabe anpassen."],
  ["Was zählt als Anfrage?", "Eine Anfrage entspricht einem Teil mit einem PDF- und STEP-Paar. Mehrere Stückzahlen für dasselbe Teil zählen als eine Anfrage."],
  ["Kann mein Team mitarbeiten?", "Teammitglieder teilen sich Anfragen, Angebote und Einstellungen mit rollenbasiertem Zugriff. Die Teamfunktion ist in allen Tarifen verfügbar."],
  ["Wie funktioniert der Test?", "Sie können Vinyos Quote 7 Tage kostenlos mit 25 Anfragen testen. Registrieren Sie sich und kalkulieren Sie Ihre eigenen Bauteile."],
];

export default function WebsiteContent() {
  return (
    <div className="vc">
      <style>{CSS}</style>
      <ContactWidget />
      <section className="vc-pricing vc-section" id="preise">
        <div className="vc-section-label">PREISE</div><div className="vc-section-head"><h2>Passend zu<br /><em>Ihren Anfragen.</em></h2><p>Testen Sie Vinyos Quote 7 Tage kostenlos mit 25 Anfragen. Alle Tarife sind monatlich kündbar.</p></div>
        <div className="vc-plans">{PLANS.map((plan) => {
          const params = new URLSearchParams({ view: "signup", next: `/einstellungen/tarif?plan=${plan.id}&mode=${plan.trial ? "trial" : "direct"}` });
          return <article key={plan.id} className={plan.trial ? "vc-plan vc-plan-trial" : "vc-plan"}><div className="vc-plan-top"><h3>{plan.name}</h3>{plan.trial && <span>7 TAGE GRATIS</span>}</div><div className="vc-price">{plan.price} € <span>/ Monat</span></div><p>{plan.count} Anfragen pro Monat</p><a href={`${LOGIN_URL}?${params}`} className={plan.trial ? "vc-button vc-button-primary" : "vc-button"}>{plan.trial ? "Kostenlos testen" : "Tarif wählen"}<span>↗</span></a><ul><li>Weitere Anfragen: 1,00 €</li><li>Vollständige Analyse</li><li>3D-Viewer und PDF-Export</li><li>Unbegrenzte Maschinen</li><li>{plan.feature}</li></ul></article>;
        })}</div><p className="vc-pricing-note">Sie benötigen mehr als 700 Anfragen pro Monat? <a href="mailto:kontakt@vinyos.de">Fragen Sie Ihren individuellen Tarif an.</a></p>
      </section>

      <section className="vc-faq vc-section" id="fragen"><div><div className="vc-section-label">GUT ZU WISSEN</div><h2>Ihre Fragen.<br /><em>Unsere Antworten.</em></h2><a href={DEMO_URL} className="vc-text-link">Persönliche Demo buchen <span>↗</span></a></div><div>{FAQ.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}<a className="vc-privacy" href="/datenschutz">Informationen zum Schutz Ihrer Daten ↗</a></div></section>

      <section className="vc-final" id="kontakt"><div className="vc-section-label">VOM BAUTEIL ZUM ANGEBOT</div><h2>Ihr nächstes Teil.<br /><em>Ihre erste Kalkulation.</em></h2><p>Testen Sie Vinyos Quote mit Ihren eigenen Dreh- und Frästeilen.</p><a href={SIGNUP_URL} className="vc-button vc-button-primary">Kostenlos testen <span>↗</span></a><small>7 Tage · 25 Anfragen kostenlos</small><a className="vc-demo" href={DEMO_URL}>Oder buchen Sie eine persönliche Demo.</a></section>
      <footer className="vc-footer"><a href="#entdecken" className="vc-wordmark">Vinyos <span>Quote</span></a><div><a href="mailto:kontakt@vinyos.de">Kontakt</a><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/agb">AGB</a></div><span>Vinyos AI UG (haftungsbeschränkt)</span></footer>
    </div>
  );
}

const CSS = `
.vc{background:var(--hm-bg);color:var(--hm-text);font-family:var(--hm-body);line-height:1.6}.vc *{box-sizing:border-box}.vc-section{padding:110px 6%;scroll-margin-top:25px}.vc-section-label{font:10px var(--hm-mono);letter-spacing:1.6px;color:var(--hm-petrol);margin-bottom:36px}.vc h2{font:500 clamp(32px,4.3vw,66px)/1.09 var(--hm-display);letter-spacing:-.045em;margin:0}.vc h2 em{font-style:normal;color:var(--hm-muted)}.vc p{font-size:14px;color:var(--hm-muted);line-height:1.85}.vc h3{font:500 20px/1.3 var(--hm-display);letter-spacing:-.025em;margin:25px 0 14px}.vc-section-head{display:grid;grid-template-columns:1.2fr 1fr;gap:12%;align-items:end;margin-bottom:64px}.vc-section-head p{max-width:400px;margin:0}.vc a:focus-visible,.vc summary:focus-visible{outline:2px solid var(--hm-petrol);outline-offset:5px}.vc-process{background:var(--hm-paper);color:var(--hm-ink)}.vc-process .vc-section-label{color:var(--hm-dark-petrol)}.vc-process h2 em,.vc-process p{color:var(--hm-ink-muted)}
.vc-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:5%}.vc-steps article{border-top:1px solid var(--hm-paper-line);padding-top:24px}.vc-step-number{font:11px var(--hm-mono);color:var(--hm-dark-petrol)}.vc-steps p{max-width:340px;font-size:13px}.vc-files,.vc-analysis,.vc-offer{height:150px;max-width:280px;margin:28px 0;display:flex;flex-direction:column;justify-content:center;font:11px var(--hm-mono)}.vc-files span{display:flex;justify-content:space-between;border:1px solid var(--hm-paper-line);padding:17px;margin-bottom:8px}.vc-files span:nth-child(2){transform:translateX(14px)}.vc-files b{font-size:9px;color:var(--hm-dark-petrol)}.vc-analysis span{padding:12px 0;border-bottom:1px solid var(--hm-paper-line);display:flex;justify-content:space-between}.vc-analysis i{font-style:normal;color:var(--hm-dark-petrol)}.vc-offer{border:1px solid var(--hm-paper-line);padding:20px}.vc-offer>span{letter-spacing:2px;font-size:9px}.vc-offer>div{width:70%;height:1px;background:var(--hm-paper-line);margin-top:13px}.vc-offer>div+div{width:45%}.vc-offer b{font-weight:400;color:var(--hm-dark-petrol);margin-top:18px;font-size:10px}
.vc-calculation{display:grid;grid-template-columns:1fr 1fr;gap:12%;align-items:center;border-bottom:1px solid var(--hm-line)}.vc-calculation p{max-width:380px;margin:30px 0}.vc-text-link{font-size:12px;color:var(--hm-text);text-decoration:none;border-bottom:1px solid var(--hm-line);padding-bottom:10px;display:inline-flex;gap:35px}.vc-text-link span{color:var(--hm-petrol)}.vc-costs-head{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;font:9px var(--hm-mono);letter-spacing:1px;color:var(--hm-petrol);border-bottom:1px solid var(--hm-line);padding-bottom:20px}.vc-costs-head span{color:var(--hm-muted);font-size:8px}.vc-cost-row{display:flex;gap:24px;align-items:center;border-bottom:1px solid var(--hm-line);padding:20px 0}.vc-cost-row span{font:10px var(--hm-mono);color:var(--hm-muted)}.vc-cost-row span:last-child{margin-left:auto;color:var(--hm-petrol)}.vc-cost-row strong{font-size:14px;font-weight:400}.vc-costs-foot{font:10px/1.8 var(--hm-mono);color:var(--hm-muted);padding-top:22px}
.vc-features{display:grid;grid-template-columns:repeat(3,1fr);gap:45px 5%}.vc-features article{border-top:1px solid var(--hm-line);padding-top:22px}.vc-features article>span{font:10px var(--hm-mono);color:var(--hm-petrol)}.vc-features p{font-size:13px;max-width:330px}.vc-features h3{font-size:19px}
.vc-pricing{background:color-mix(in srgb,var(--hm-line) 18%,var(--hm-bg))}.vc-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.vc-plan{padding:30px;border:1px solid var(--hm-line);border-radius:4px}.vc-plan-trial{border-color:var(--hm-petrol)}.vc-plan-top{display:flex;justify-content:space-between;align-items:center;gap:15px}.vc-plan-top h3{margin:0}.vc-plan-top>span{color:var(--hm-petrol);font:8px var(--hm-mono);letter-spacing:1px}.vc-price{font:500 clamp(34px,3.4vw,52px) var(--hm-display);letter-spacing:-2px;margin-top:40px}.vc-price span{font:11px var(--hm-body);letter-spacing:0;color:var(--hm-muted)}.vc-plan>p{font-size:12px;margin:8px 0 28px}.vc-button{display:flex;align-items:center;justify-content:space-between;gap:35px;padding:13px 18px;border:1px solid var(--hm-line);border-radius:4px;color:var(--hm-text);font-size:12px;text-decoration:none}.vc-button-primary{background:var(--hm-petrol);color:var(--hm-bg);border-color:var(--hm-petrol)}.vc-button:hover{border-color:var(--hm-petrol);filter:brightness(1.1)}.vc-plan ul{list-style:none;padding:25px 0 0;margin:0;font-size:12px;color:var(--hm-muted)}.vc-plan li{padding:6px 0}.vc-plan li:before{content:'✓';margin-right:12px;color:var(--hm-petrol)}.vc-pricing-note{font-size:12px!important;margin:30px 0 0}.vc-pricing-note a{color:var(--hm-text);text-underline-offset:4px}
.vc-faq{display:grid;grid-template-columns:1fr 1fr;gap:10%}.vc-faq .vc-text-link{margin-top:35px}.vc-faq details{border-top:1px solid var(--hm-line)}.vc-faq summary{cursor:pointer;padding:23px 0;list-style:none;font-size:14px;display:flex;justify-content:space-between;gap:20px}.vc-faq summary::-webkit-details-marker{display:none}.vc-faq summary span{color:var(--hm-petrol);font-size:18px;line-height:1}.vc-faq details[open] summary span{transform:rotate(45deg)}.vc-faq details p{font-size:13px;margin:0 0 24px}.vc-privacy{display:inline-block;margin-top:20px;font-size:11px;color:var(--hm-muted);text-underline-offset:5px}.vc-final{text-align:center;border-top:1px solid var(--hm-line);padding:120px 6%}.vc-final .vc-button{width:230px;margin:30px auto 12px}.vc-final>small{display:block;font:10px var(--hm-mono);color:var(--hm-muted)}.vc-final .vc-demo{display:inline-block;font-size:11px;color:var(--hm-muted);margin-top:30px;text-underline-offset:5px}.vc-footer{margin:0 6%;padding:35px 0;border-top:1px solid var(--hm-line);display:flex;align-items:center;justify-content:space-between;gap:25px}.vc-wordmark{font:500 23px var(--hm-display);letter-spacing:-1px;text-decoration:none;color:var(--hm-text)}.vc-wordmark span{font-size:12px;letter-spacing:0;color:var(--hm-muted)}.vc-footer>div{display:flex;gap:25px}.vc-footer>div a{font-size:10px;color:var(--hm-muted);text-decoration:none}.vc-footer>span{font:8px var(--hm-mono);color:var(--hm-muted)}
@media(max-width:1000px){.vc-section{padding:80px 6%}.vc-section-head{gap:6%}.vc-plans{gap:12px}.vc-plan{padding:22px}.vc-plan-top{align-items:flex-start;flex-direction:column}.vc-calculation{gap:6%}.vc-footer{flex-wrap:wrap}}
@media(max-width:759px){.vc-section{padding:64px 7%}.vc-section-label{font-size:9px;margin-bottom:25px}.vc-section-head,.vc-calculation,.vc-faq{grid-template-columns:1fr;gap:32px}.vc-section-head{margin-bottom:38px}.vc h2{font-size:35px}.vc p{font-size:13px}.vc-steps,.vc-plans{grid-template-columns:1fr;gap:30px}.vc-steps article{display:grid;grid-template-columns:1fr 1fr;column-gap:18px}.vc-step-number{grid-column:1/-1}.vc-steps article h3{grid-column:1;grid-row:2;margin-top:22px}.vc-steps article p{grid-column:1;grid-row:3;margin:0}.vc-files,.vc-analysis,.vc-offer{grid-column:2;grid-row:2/4;margin:25px 0;font-size:9px;align-self:center}.vc-files span{padding:14px 8px}.vc-files span:nth-child(2){transform:translateX(5px)}.vc-offer{padding:14px}.vc-offer b{font-size:9px}.vc-features{grid-template-columns:1fr;gap:28px}.vc-features article{display:grid;grid-template-columns:30px 1fr;column-gap:15px}.vc-features h3{margin:0 0 12px}.vc-features p{grid-column:2;margin:0;max-width:none}.vc-plan{padding:27px}.vc-plan-top{flex-direction:row;align-items:center}.vc-price{font-size:45px;margin-top:25px}.vc-faq{gap:38px}.vc-final{padding:80px 7%}.vc-final h2{font-size:36px}.vc-footer{margin:0 7%;flex-direction:column;align-items:flex-start;gap:22px}.vc-footer>div{gap:22px}.vc-footer>span{font-size:8px}}
`;
