import ContactWidget from "./ContactWidget";
import { LOGIN_URL, SIGNUP_URL } from "./story";

const DEMO_URL = "https://calendly.com/kontakt-vinyos/30min";

// Inhalte aus der bestehenden Marketingseite, sprachlich für den neuen Entwurf überarbeitet.
const PLANS = [
  { name: "Starter", id: "starter", price: "189", count: "150", feature: "Team-Mitglieder", trial: true },
  { name: "Pro", id: "pro", price: "349", count: "350", feature: "Team-Mitglieder", trial: false },
  { name: "Enterprise", id: "enterprise", price: "579", count: "700", feature: "Prioritäts-Support", trial: false },
];
const FAQ = [
  ["Welche Dateien benötige ich?", "Vinyos Quote verarbeitet technische Zeichnungen als PDF und 3D-Modelle im STEP-Format (.stp oder .step). Wenn die Dateinamen übereinstimmen, werden PDF und STEP automatisch als Paar erkannt."],
  ["Wie entsteht der Preis?", "Die Kalkulation berechnet Schnittzeiten, Rüstkosten und Material regelbasiert mit Ihren Stundensätzen und Ihrer Marge. Sie prüfen den Vorschlag und können ihn vor der Freigabe anpassen."],
  ["Was zählt als Anfrage?", "Eine Anfrage entspricht einem Teil mit einem PDF- und STEP-Paar. Mehrere Stückzahlen für dasselbe Teil zählen als eine Anfrage."],
  ["Kann mein Team mitarbeiten?", "Teammitglieder teilen sich Anfragen, Angebote und Einstellungen mit rollenbasiertem Zugriff. Die Teamfunktion ist in allen Tarifen verfügbar."],
  ["Wie funktioniert der Test?", "Sie können Vinyos Quote 7 Tage kostenlos mit 25 Anfragen testen. Registrieren Sie sich und kalkulieren Sie Ihre eigenen Bauteile."],
];

export default function WebsiteContent() {
  return (
    <div className="vc">
      <style>{CSS}</style>
      <ContactWidget />
      <section className="vc-pricing vc-section" id="preise">
        <div className="vc-section-label">PREISE</div><div className="vc-section-head"><h2>Passend zu<br /><em>Ihren Anfragen.</em></h2><p>Testen Sie Vinyos Quote 7 Tage kostenlos mit 25 Anfragen. Alle Tarife sind monatlich kündbar.</p></div>
        <div className="vc-plans">{PLANS.map((plan) => {
          const params = new URLSearchParams({ view: "signup", next: `/einstellungen/tarif?plan=${plan.id}&mode=${plan.trial ? "trial" : "direct"}` });
          return <article key={plan.id} className={plan.trial ? "vc-plan vc-plan-trial" : "vc-plan"}><div className="vc-plan-top"><h3>{plan.name}</h3>{plan.trial && <span>7 TAGE GRATIS</span>}</div><div className="vc-price">{plan.price} € <span>/ Monat</span></div><p>{plan.count} Anfragen pro Monat</p><a href={`${LOGIN_URL}?${params}`} className={plan.trial ? "vc-button vc-button-primary" : "vc-button"}>{plan.trial ? "Kostenlos testen" : "Tarif wählen"}<span>↗</span></a><ul><li>Weitere Anfragen: 1,00 €</li><li>Vollständige Analyse</li><li>3D-Viewer und PDF-Export</li><li>Unbegrenzte Maschinen</li><li>{plan.feature}</li></ul></article>;
        })}</div><p className="vc-pricing-note">Sie benötigen mehr als 700 Anfragen pro Monat? <a href="mailto:kontakt@vinyos.de">Fragen Sie Ihren individuellen Tarif an.</a></p>
      </section>

      <section className="vc-faq vc-section" id="fragen"><div><div className="vc-section-label">GUT ZU WISSEN</div><h2>Ihre Fragen.<br /><em>Unsere Antworten.</em></h2><a href={DEMO_URL} className="vc-text-link">Persönliche Demo buchen <span>↗</span></a><a href={SIGNUP_URL} className="vc-button vc-button-primary vc-faq-cta">Kostenlos testen <span>↗</span></a><small className="vc-faq-note">7 Tage · 25 Anfragen kostenlos</small></div><div>{FAQ.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}<a className="vc-privacy" href="/datenschutz">Informationen zum Schutz Ihrer Daten ↗</a></div></section>

      <footer className="vc-footer"><a href="#entdecken" className="vc-wordmark">vinyos <span>QUOTE</span></a><div><a href="mailto:kontakt@vinyos.de">Kontakt</a><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/agb">AGB</a></div><span>Vinyos AI UG (haftungsbeschränkt)</span></footer>
    </div>
  );
}

const CSS = `
.vc{--vc-gutter:max(6%,calc((100% - 980*var(--hm-u))/2));background:var(--hm-bg);color:var(--hm-text);font-family:var(--hm-body);line-height:1.6}.vc *{box-sizing:border-box}.vc-section{padding:calc(90*var(--hm-u)) var(--vc-gutter);scroll-margin-top:calc(25*var(--hm-u))}.vc-section-label{font:calc(13*var(--hm-u)) var(--hm-mono);letter-spacing:1.6px;color:var(--hm-petrol);margin-bottom:calc(36*var(--hm-u))}.vc h2{font:500 clamp(calc(32*var(--hm-u)),3.6vw,calc(56*var(--hm-u)))/1.09 var(--hm-display);letter-spacing:-.045em;margin:0}.vc h2 em{font-style:normal;color:var(--hm-muted)}.vc p{font-size:calc(15*var(--hm-u));color:var(--hm-muted);line-height:1.85}.vc h3{font:500 calc(20*var(--hm-u))/1.3 var(--hm-display);letter-spacing:-.025em;margin:calc(25*var(--hm-u)) 0 calc(14*var(--hm-u))}.vc-section-head{display:grid;grid-template-columns:1.2fr 1fr;gap:12%;align-items:end;margin-bottom:calc(48*var(--hm-u))}.vc-section-head p{max-width:calc(400*var(--hm-u));margin:0}.vc a:focus-visible,.vc summary:focus-visible{outline:2px solid var(--hm-petrol);outline-offset:calc(5*var(--hm-u))}.vc-process{background:var(--hm-paper);color:var(--hm-ink)}.vc-process .vc-section-label{color:var(--hm-dark-petrol)}.vc-process h2 em,.vc-process p{color:var(--hm-ink-muted)}
.vc-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:5%}.vc-steps article{border-top:1px solid var(--hm-paper-line);padding-top:calc(24*var(--hm-u))}.vc-step-number{font:calc(13*var(--hm-u)) var(--hm-mono);color:var(--hm-dark-petrol)}.vc-steps p{max-width:calc(340*var(--hm-u));font-size:calc(15*var(--hm-u))}.vc-files,.vc-analysis,.vc-offer{height:calc(150*var(--hm-u));max-width:calc(280*var(--hm-u));margin:calc(28*var(--hm-u)) 0;display:flex;flex-direction:column;justify-content:center;font:calc(13*var(--hm-u)) var(--hm-mono)}.vc-files span{display:flex;justify-content:space-between;border:1px solid var(--hm-paper-line);padding:calc(17*var(--hm-u));margin-bottom:calc(8*var(--hm-u))}.vc-files span:nth-child(2){transform:translateX(calc(14*var(--hm-u)))}.vc-files b{font-size:calc(12*var(--hm-u));color:var(--hm-dark-petrol)}.vc-analysis span{padding:calc(12*var(--hm-u)) 0;border-bottom:1px solid var(--hm-paper-line);display:flex;justify-content:space-between}.vc-analysis i{font-style:normal;color:var(--hm-dark-petrol)}.vc-offer{border:1px solid var(--hm-paper-line);padding:calc(20*var(--hm-u))}.vc-offer>span{letter-spacing:2px;font-size:calc(12*var(--hm-u))}.vc-offer>div{width:70%;height:1px;background:var(--hm-paper-line);margin-top:calc(13*var(--hm-u))}.vc-offer>div+div{width:45%}.vc-offer b{font-weight:400;color:var(--hm-dark-petrol);margin-top:calc(18*var(--hm-u));font-size:calc(13*var(--hm-u))}
.vc-calculation{display:grid;grid-template-columns:1fr 1fr;gap:12%;align-items:center;border-bottom:1px solid var(--hm-line)}.vc-calculation p{max-width:calc(380*var(--hm-u));margin:calc(30*var(--hm-u)) 0}.vc-text-link{font-size:calc(14*var(--hm-u));color:var(--hm-text);text-decoration:none;border-bottom:1px solid var(--hm-line);padding-bottom:calc(10*var(--hm-u));display:inline-flex;gap:calc(35*var(--hm-u))}.vc-text-link span{color:var(--hm-petrol)}.vc-faq>div:first-child{display:flex;flex-direction:column;align-items:flex-start}.vc .vc-faq-cta{margin-top:calc(28*var(--hm-u));min-width:calc(230*var(--hm-u))}.vc-faq-note{display:block;margin-top:calc(12*var(--hm-u));font:calc(13*var(--hm-u)) var(--hm-mono);color:var(--hm-muted)}.vc-costs-head{display:flex;flex-wrap:wrap;justify-content:space-between;gap:calc(10*var(--hm-u));font:calc(12*var(--hm-u)) var(--hm-mono);letter-spacing:1px;color:var(--hm-petrol);border-bottom:1px solid var(--hm-line);padding-bottom:calc(20*var(--hm-u))}.vc-costs-head span{color:var(--hm-muted);font-size:calc(11*var(--hm-u))}.vc-cost-row{display:flex;gap:calc(24*var(--hm-u));align-items:center;border-bottom:1px solid var(--hm-line);padding:calc(20*var(--hm-u)) 0}.vc-cost-row span{font:calc(13*var(--hm-u)) var(--hm-mono);color:var(--hm-muted)}.vc-cost-row span:last-child{margin-left:auto;color:var(--hm-petrol)}.vc-cost-row strong{font-size:calc(15*var(--hm-u));font-weight:400}.vc-costs-foot{font:calc(13*var(--hm-u))/1.8 var(--hm-mono);color:var(--hm-muted);padding-top:calc(22*var(--hm-u))}
.vc-features{display:grid;grid-template-columns:repeat(3,1fr);gap:calc(45*var(--hm-u)) 5%}.vc-features article{border-top:1px solid var(--hm-line);padding-top:calc(22*var(--hm-u))}.vc-features article>span{font:calc(13*var(--hm-u)) var(--hm-mono);color:var(--hm-petrol)}.vc-features p{font-size:calc(15*var(--hm-u));max-width:calc(330*var(--hm-u))}.vc-features h3{font-size:calc(19*var(--hm-u))}
.vc-pricing{background:color-mix(in srgb,var(--hm-line) 18%,var(--hm-bg))}.vc-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:calc(20*var(--hm-u))}.vc-plan{padding:calc(24*var(--hm-u));border:1px solid var(--hm-line);border-radius:calc(4*var(--hm-u))}.vc-plan-trial{border-color:var(--hm-petrol)}.vc-plan-top{display:flex;justify-content:space-between;align-items:center;gap:calc(15*var(--hm-u))}.vc-plan-top h3{margin:0}.vc-plan-top>span{color:var(--hm-petrol);font:calc(11*var(--hm-u)) var(--hm-mono);letter-spacing:1px}.vc-price{font:500 clamp(calc(34*var(--hm-u)),3vw,calc(44*var(--hm-u))) var(--hm-display);letter-spacing:-2px;margin-top:calc(24*var(--hm-u))}.vc-price span{font:calc(13*var(--hm-u)) var(--hm-body);letter-spacing:0;color:var(--hm-muted)}.vc-plan>p{font-size:calc(14*var(--hm-u));margin:calc(6*var(--hm-u)) 0 calc(20*var(--hm-u))}.vc-button{display:flex;align-items:center;justify-content:space-between;gap:calc(35*var(--hm-u));padding:calc(13*var(--hm-u)) calc(18*var(--hm-u));border:1px solid var(--hm-line);border-radius:calc(4*var(--hm-u));color:var(--hm-text);font-size:calc(14*var(--hm-u));text-decoration:none}.vc-button-primary{background:var(--hm-petrol);color:var(--hm-bg);border-color:var(--hm-petrol)}.vc-button:hover{border-color:var(--hm-petrol);filter:brightness(1.1)}.vc-plan ul{list-style:none;padding:calc(18*var(--hm-u)) 0 0;margin:0;font-size:calc(14*var(--hm-u));color:var(--hm-muted)}.vc-plan li{padding:calc(4*var(--hm-u)) 0}.vc-plan li:before{content:'✓';margin-right:calc(12*var(--hm-u));color:var(--hm-petrol)}.vc-pricing-note{font-size:calc(14*var(--hm-u))!important;margin:calc(30*var(--hm-u)) 0 0}.vc-pricing-note a{color:var(--hm-text);text-underline-offset:calc(4*var(--hm-u))}
.vc-faq{display:grid;grid-template-columns:1fr 1fr;gap:10%}.vc-faq .vc-text-link{margin-top:calc(35*var(--hm-u))}.vc-faq details{border-top:1px solid var(--hm-line)}.vc-faq summary{cursor:pointer;padding:calc(23*var(--hm-u)) 0;list-style:none;font-size:calc(15*var(--hm-u));display:flex;justify-content:space-between;gap:calc(20*var(--hm-u))}.vc-faq summary::-webkit-details-marker{display:none}.vc-faq summary span{color:var(--hm-petrol);font-size:calc(18*var(--hm-u));line-height:1}.vc-faq details[open] summary span{transform:rotate(45deg)}.vc-faq details p{font-size:calc(15*var(--hm-u));margin:0 0 calc(24*var(--hm-u))}.vc-privacy{display:inline-block;margin-top:calc(20*var(--hm-u));font-size:calc(13*var(--hm-u));color:var(--hm-muted);text-underline-offset:calc(5*var(--hm-u))}.vc-footer{margin:0 var(--vc-gutter);padding:calc(35*var(--hm-u)) 0;border-top:1px solid var(--hm-line);display:flex;align-items:center;justify-content:space-between;gap:calc(25*var(--hm-u))}.vc-wordmark{font:500 calc(23*var(--hm-u)) var(--hm-display);letter-spacing:-1px;text-decoration:none;color:var(--hm-text)}.vc-wordmark span{font-size:calc(14*var(--hm-u));letter-spacing:.8px;color:var(--hm-muted)}.vc-footer>div{display:flex;gap:calc(25*var(--hm-u))}.vc-footer>div a{font-size:calc(13*var(--hm-u));color:var(--hm-muted);text-decoration:none}.vc-footer>span{font:calc(11*var(--hm-u)) var(--hm-mono);color:var(--hm-muted)}
@media(max-width:1000px){.vc-section{padding:calc(80*var(--hm-u)) 6%}.vc-section-head{gap:6%}.vc-plans{gap:calc(12*var(--hm-u))}.vc-plan{padding:calc(22*var(--hm-u))}.vc-plan-top{align-items:flex-start;flex-direction:column}.vc-calculation{gap:6%}.vc-footer{flex-wrap:wrap}}
@media(max-width:759px){.vc-section{padding:calc(64*var(--hm-u)) 7%}.vc-section-label{font-size:calc(12*var(--hm-u));margin-bottom:calc(25*var(--hm-u))}.vc-section-head,.vc-calculation,.vc-faq{grid-template-columns:1fr;gap:calc(32*var(--hm-u))}.vc-section-head{margin-bottom:calc(38*var(--hm-u))}.vc h2{font-size:calc(35*var(--hm-u))}.vc p{font-size:calc(15*var(--hm-u))}.vc-steps,.vc-plans{grid-template-columns:1fr;gap:calc(30*var(--hm-u))}.vc-steps article{display:grid;grid-template-columns:1fr 1fr;column-gap:calc(18*var(--hm-u))}.vc-step-number{grid-column:1/-1}.vc-steps article h3{grid-column:1;grid-row:2;margin-top:calc(22*var(--hm-u))}.vc-steps article p{grid-column:1;grid-row:3;margin:0}.vc-files,.vc-analysis,.vc-offer{grid-column:2;grid-row:2/4;margin:calc(25*var(--hm-u)) 0;font-size:calc(12*var(--hm-u));align-self:center}.vc-files span{padding:calc(14*var(--hm-u)) calc(8*var(--hm-u))}.vc-files span:nth-child(2){transform:translateX(calc(5*var(--hm-u)))}.vc-offer{padding:calc(14*var(--hm-u))}.vc-offer b{font-size:calc(12*var(--hm-u))}.vc-features{grid-template-columns:1fr;gap:calc(28*var(--hm-u))}.vc-features article{display:grid;grid-template-columns:calc(30*var(--hm-u)) 1fr;column-gap:calc(15*var(--hm-u))}.vc-features h3{margin:0 0 calc(12*var(--hm-u))}.vc-features p{grid-column:2;margin:0;max-width:none}.vc-plan{padding:calc(27*var(--hm-u))}.vc-plan-top{flex-direction:row;align-items:center}.vc-price{font-size:calc(45*var(--hm-u));margin-top:calc(25*var(--hm-u))}.vc-faq{gap:calc(38*var(--hm-u))}.vc-footer{margin:0 7%;flex-direction:column;align-items:flex-start;gap:calc(22*var(--hm-u))}.vc-footer>div{gap:calc(22*var(--hm-u))}.vc-footer>span{font-size:calc(11*var(--hm-u))}}
`;
